volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:

networks:
  internal:

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ['internal']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:2.37.7
    hostname: n8n
    container_name: n8n
    networks: ['internal']
    restart: unless-stopped
    ports:
      - 8080:5678
    environment:
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama:11434}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/London}
      - TZ=${TZ:-Europe/London}
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    env_file:
      - path: .env
        required: true
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started

  qdrant:
    image: qdrant/qdrant:v1.19.0
    hostname: qdrant
    container_name: qdrant
    networks: ['internal']
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    container_name: ollama
    networks: ['internal']
    restart: unless-stopped
    ports:
      - 127.0.0.1:11434:11434
    volumes:
      - ollama_storage:/root/.ollama

  ollama-pull-llama:
    image: ollama/ollama:latest
    container_name: ollama-pull-llama
    networks: ['internal']
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    environment:
      - OLLAMA_HOST=ollama:11434
    command:
      - "-c"
      - "until ollama list >/dev/null 2>&1; do sleep 1; done; ollama pull llama3.2"
    depends_on:
      - ollama
